### ISSUE TITLE
The word-wrap of the title is not correct.

### ISSUE THREAD

**Issue by zheng1** [openpitrix/openpitrix.github.io#39]
![wx20180308-105216](https://user-images.githubusercontent.com/4156721/37130528-cb8d34ac-22be-11e8-9466-fcf9bdece1da.png)

https://github.com/openpitrix/openpitrix.github.io/blob/a3739c7499c0330180b7f9de4d17d25b5e7346b2/static/css/style.css#L19-L27

## Need a space after the comma in the text below.

https://github.com/openpitrix/openpitrix.github.io/blob/a3739c7499c0330180b7f9de4d17d25b5e7346b2/config.toml#L68-L70
https://github.com/openpitrix/openpitrix.github.io/blob/a3739c7499c0330180b7f9de4d17d25b5e7346b2/config.toml#L139-L141

**Comment by libangrui** [comment]
solved
